In [1]:
cd ~/src_aiai/

/lustre/home/ucapmm6/src_aiai


In [2]:
%load_ext autoreload

In [3]:
%autoreload 2
%aimport src.dataset

Failed to import NUDFT_cupy (experimental). Use NUDFT() instead. 


In [4]:
from src.dataset import *
from src.data import load_M51
from src.visualisation import *

In [5]:
import tensorflow as tf

In [26]:
from skimage import io

In [22]:
import os

In [11]:
tf.__version__

'2.0.0'

In [6]:
tf_func, func = measurement_func()


In [28]:
files = np.loadtxt(os.environ["HOME"] + "/src_aiai/images.txt", dtype=str)

data = tf.io.read_file(files[0])
data = tf.io.decode_jpeg(data, channels=1)

data2 = io.imread(files[0])


In [33]:
type(data2)

numpy.ndarray

In [39]:
data

<tf.Tensor: id=337, shape=(640, 425, 1), dtype=uint8, numpy=
array([[[  3],
        [  3],
        [ 70],
        ...,
        [ 36],
        [ 34],
        [ 38]],

       [[  0],
        [  3],
        [ 58],
        ...,
        [ 35],
        [ 44],
        [ 29]],

       [[  4],
        [  1],
        [ 12],
        ...,
        [ 49],
        [ 59],
        [ 47]],

       ...,

       [[176],
        [175],
        [183],
        ...,
        [132],
        [132],
        [129]],

       [[175],
        [173],
        [176],
        ...,
        [134],
        [133],
        [128]],

       [[170],
        [179],
        [179],
        ...,
        [132],
        [129],
        [128]]], dtype=uint8)>

In [38]:
tf.expand_dims(data, 3)

<tf.Tensor: id=342, shape=(640, 425, 1, 1), dtype=uint8, numpy=
array([[[[  3]],

        [[  3]],

        [[ 70]],

        ...,

        [[ 36]],

        [[ 34]],

        [[ 38]]],


       [[[  0]],

        [[  3]],

        [[ 58]],

        ...,

        [[ 35]],

        [[ 44]],

        [[ 29]]],


       [[[  4]],

        [[  1]],

        [[ 12]],

        ...,

        [[ 49]],

        [[ 59]],

        [[ 47]]],


       ...,


       [[[176]],

        [[175]],

        [[183]],

        ...,

        [[132]],

        [[132]],

        [[129]]],


       [[[175]],

        [[173]],

        [[176]],

        ...,

        [[134]],

        [[133]],

        [[128]]],


       [[[170]],

        [[179]],

        [[179]],

        ...,

        [[132]],

        [[129]],

        [[128]]]], dtype=uint8)>

In [32]:
type(tf.convert_to_tensor(data2))

tensorflow.python.framework.ops.EagerTensor

In [7]:
test_im = load_M51()

In [8]:
t = tf.convert_to_tensor(test_im)

In [9]:
a = tf_func(t)

    @tf.function(input_signature=[tf.TensorSpec(None, tf.float32)])
    def tf_function(x):
#         return tf.numpy_function(func, [x], ((tf.float32, tf.complex64), tf.float32))
        return tf.numpy_function(func, [x], (tf.float32, tf.complex64, tf.float32))

This may be caused by multiline strings or comments not indented at the same level as the code.
    @tf.function(input_signature=[tf.TensorSpec(None, tf.float32)])
    def tf_function(x):
#         return tf.numpy_function(func, [x], ((tf.float32, tf.complex64), tf.float32))
        return tf.numpy_function(func, [x], (tf.float32, tf.complex64, tf.float32))

This may be caused by multiline strings or comments not indented at the same level as the code.
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [13]:
ds = Dataset(3)


In [14]:
def data_map(x,y,z):
    """split input and output of train data"""
    return (x,y), z

In [20]:
data = ds.cache().map(crop).map(tf_func).shuffle(3, reshuffle_each_iteration=True).batch(3).map(data_map).prefetch(tf.data.experimental.AUTOTUNE)


In [18]:
data

<DatasetV1Adapter shapes: (<unknown>, <unknown>, <unknown>), types: (tf.float32, tf.complex64, tf.float32)>

In [21]:
for i in data:
    print(i)
#     compare([i[0][0], np.log(i[1][0].numpy().real), i[2][0]])

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
((<tf.Tensor: id=326, shape=(3, 256, 256, 1), dtype=float32, numpy=
array([[[[-0.02031953],
         [ 0.02104558],
         [ 0.03085409],
         ...,
         [ 0.0168053 ],
         [ 0.01066069],
         [-0.02682906]],

        [[-0.01350125],
         [ 0.03038704],
         [ 0.04221547],
         ...,
         [ 0.02900864],
         [ 0.02032107],
         [-0.02221267]],

        [[-0.00805928],
         [ 0.03694563],
         [ 0.04989913],
         ...,
         [ 0.03868145],
         [ 0.02844756],
         [-0.01705787]],

        ...,

        [[ 0.02287173],
         [ 0.08172802],
         [ 0.10312425],
         ...,
         [ 0.10245915],
         [ 0.07536282],
         [ 0.01636592]],

        [[ 0.00669039],
         [ 0.06058293],
         [ 0.07887292],
         ...,
         [ 0.07799463],
         [ 0.05289789],


In [ ]:
i[1][0].numpy

In [ ]:
fft = lambda x: tf.signal.fftshift(tf.signal.fft2d(tf.signal.fftshift(x, axes=(-2,-1))), axes=(-2,-1))


In [ ]:
a = x_true[:,:,0]

In [ ]:
b = fft(tf.cast(a, tf.complex64))

In [ ]:
plt.imshow(np.log(b.numpy().real))

In [ ]:
fft2 = lambda x: np.fft.fftshift(np.fft.fft2(np.fft.fftshift(x), norm='ortho'))

In [ ]:
c = fft2(a.numpy())

In [ ]:
plt.imshow(np.log(c.imag))